[project]
name = "fluffy-waddle"
description = ""
readme = "README.md"
requires-python = ">=3.11, <3.15"
authors = [
  { name = "hcubasd", email = "127428549+hcubasd@users.noreply.github.com" },
]
urls = { Repository = "https://github.com/hcubasd/fluffy-waddle" }
dependencies = ["pydantic~=2.13.0"]
dynamic = ["version"]

[build-system]
requires = ["hatch-vcs", "hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0"
